function reconnectedfile=elongatetrack(file, maxblink, distmax, minpoints, handles); 
% function reconnectedfile=elongatetrack(file, maxblink, distmax, minpoints, handles); 
% Takes .trc files generated by initial tracking
% calls reconnectfast.m to reconnect trajectories 
%
% Marianne Renner mar 09 - for SPTrack v4
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

warning off MATLAB:MKDIR:DirectoryExists
path=cd;
control=1;
[namefile,rem]=strtok(file,'.');

%reconnection
disp('  ');
disp('Reconnecting trajectories...');
waitbarhandle=waitbar( 0,'Please wait...','Name',['Reconnecting trajectories in ',file]);
[reconnectedfile]=reconnectfast(path,file,maxblink,distmax,minpoints,handles,waitbarhandle);
close(waitbarhandle);

if (length(reconnectedfile)>0) 
   %save everything
   save(['trc\',namefile,'.con.trc'],'reconnectedfile','-ascii');
 else
  disp('Empty .con.trc file');
  %report
  text=['No trajectories to reconnect...'];
  updatereport(handles,text,1)
end

%end of file


